/* Automatically generated by 'scrips//build-entry.js' */
import About from '../views/About.vue';
const Home = () => import('../views/Home.vue');
const New = () => import('../views/New.vue');

const routes = [
    {
        path: '/About',
        name: 'About', 
        component: About
    },
    {
        path: '/Home',
        name: 'Home', 
        component: Home
    },
    {
        path: '/New',
        name: 'New', 
        component: New
    }
];

export default routes;
