const pages = require('../src/router/router.json');
const path = require('path');
const fs = require('fs');

const OUTPUT_PATH = path.join(__dirname, '../src/router/router-config.js');

const pageTemplate = [];
const listTemplate = []
const fourTab = '    ';
const eightTab = '        ';
pages.forEach((page, index) => {
    const pageName = page.name;
    if (index === 0) {
        pageTemplate.push(
            `import ${pageName} from '${page.path}';`
        );
        listTemplate.push(`{\n${eightTab}path: '/${pageName}',\n${eightTab}name: '${pageName}', \n${eightTab}component: ${pageName}\n${fourTab}}`);
    } else {
        pageTemplate.push(
            `const ${pageName} = () => import('../views/${pageName}.vue');`
        );
        listTemplate.push(`{\n${eightTab}path: '/${pageName}',\n${eightTab}name: '${pageName}', \n${eightTab}component: ${pageName}\n${fourTab}}`);
    }
});

const importStr = pageTemplate.join('\n');
const listTemplateStr = listTemplate.join(',\n    ');

const template = `/* Automatically generated by 'scrips//build-entry.js' */
${importStr}

const routes = [
    ${listTemplateStr}
];

export default routes;
`;
fs.writeFileSync(OUTPUT_PATH, template);
console.log('[build entry] DONE:', OUTPUT_PATH);
